resilience4j.timelimiter:
  instances:
    labService:
      timeoutDuration: 3s
      cancelRunningFuture: true
    someOtherService:
      timeoutDuration: 1s
      cancelRunningFuture: false

resilience4j.retry:
  instances:
    labService:
      maxRetryAttempts: 2
      waitDuration: 3s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
            - org.springframework.web.client.HttpClientErrorException
    OtherService:
      maxRetryAttempts: 2
      waitDuration: 3s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - org.springframework.web.client.HttpClientErrorException

---
lab:
  service:
    endpoint: http://localhost:8081/lab/